### ISSUE TITLE
Theta Tech

### ISSUE THREAD

**Issue by th3ta-tech** [mesaugat/tech-companies-in-nepal#221]
Add 
**Theta Tech**
We are an IT company based in Pokhara, offering graphic design, web design, and digital marketing services. Our team works hard to create designs, websites, and strategies that help businesses grow.
Soon, we’ll be adding more services to serve you even better. Let’s work together to bring your ideas to life!
![theta tech final logo](https://github.com/user-attachments/assets/9a6f0f4a-1285-476e-bc6e-045271bfb23a)

**Comment by mesaugat** [comment]
@th3ta-tech Please open a pull request instead of an issue. Happy to merge!
